name: Vue.js Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm install

      - name: Create .env.production file
        run: echo "VUE_APP_API_BASE_URL=${{ secrets.VUE_APP_API_BASE_URL }}" > .env.production

      - name: Build Vue.js application
        run: npm run build

      # ----------------------------------------
      # 1. 파일 전송 (scp-action    )
      - name: Deploy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/" # 빌드 결과물 폴더인 dist를 source로 지정
          target: "/var/www/html/glemoa-front/" # 서버의 배포 경로

      # ----------------------------------------
      # 2. 서버에서 명령어 실행 (ssh-action)
      - name: Execute deployment script on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Nginx 재로드
            sudo systemctl reload nginx
            echo "Deployment successful!"
